@extends('layouts.app')
@section('title','Micro Travel — Maldives, made personal')
@section('content')
@php($wa='https://wa.me/'.env('MICRO_TRAVEL_WHATSAPP','9609996210').'?text='.urlencode('Hello Micro Travel, I would like help planning a Maldives holiday.'))
<main>
@include('partials.site-nav', ['whatsAppText' => 'Hello Micro Travel, I would like help planning a Maldives holiday.'])
<section class="hero" style="background-image:url('{{ $hero->hero_image_url }}')"><div class="shade"></div><div class="hero-copy"><p class="kicker pale">{{ $hero->kicker }}</p><h1>{{ $hero->heading_line_one }}<br>{{ $hero->heading_line_two }} <em>{{ $hero->heading_emphasis }}</em></h1><p>{{ $hero->description }}</p></div>
<form class="finder" method="get" action="{{ route('accommodations.index') }}"><div class="tabs"><button type="button" class="active" data-tab="Resort">Resorts</button><button type="button" data-tab="Guesthouse">Guesthouses</button><button type="button" data-tab="Liveaboard">Liveaboards</button></div><input type="hidden" name="type" value="resort"><div class="fields"><label><small>WHERE</small><input name="atoll" placeholder="All atolls"></label><label><small>WHEN</small><input type="date" name="when"></label><label><small>TRAVELLERS</small><input type="number" name="travellers" value="2" min="1"></label><button>EXPLORE <span>→</span></button></div></form></section>
<section class="intro" id="about"><div><p class="kicker">MORE THAN A HOLIDAY</p><h2>The Maldives,<br><em>made personal.</em></h2></div><div><p>From your first question to your final seaplane, we make every detail feel effortless. Our Maldives-based team uses local knowledge to create a journey that feels entirely yours.</p><a class="under" href="{{ $wa }}" target="_blank">TALK TO A LOCAL EXPERT <span>→</span></a></div></section>
<x-why-book-with-micro-travel />
<section class="stays" id="stays"><div class="section-title"><div><p class="kicker">STAY YOUR WAY</p><h2>Places worth<br><em>travelling for.</em></h2></div><p>Resorts, guesthouses, and liveaboards selected for their character, care, and sense of place.</p></div><div class="cards">
@forelse($featuredStays as $stay) @php($image=str_starts_with($stay->cover_image,'http')?$stay->cover_image:asset('storage/'.$stay->cover_image))
<article><a href="{{ route('accommodations.show',$stay) }}"><div class="photo"><img src="{{ $image }}" alt="{{ $stay->name }}"><small>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</small></div><div class="meta"><span>{{ strtoupper($stay->type->label()) }}</span><span>{{ $stay->island }}</span></div><h3>{{ $stay->name }}</h3><div class="foot"><span>{{ $stay->tagline }}</span><b>FROM {{ $stay->currency }} {{ number_format($stay->price_from) }}</b></div></a></article>
@empty <p>Add featured accommodation from the admin panel.</p> @endforelse
</div><a class="outline" href="{{ route('accommodations.index') }}">EXPLORE ALL STAYS <span>→</span></a></section>
<section class="experience" id="experiences"><div class="exp-image"><span>▶</span></div><div class="exp-copy"><p class="kicker pale">BEYOND THE BLUE</p><h2>Come for the islands.<br><em>Remember the feeling.</em></h2><p>Drift with manta rays. Share breakfast on an empty sandbank. Learn the rhythm of island life from the people who call it home.</p><a class="under" href="{{ $wa }}" target="_blank">DISCOVER EXPERIENCES <span>→</span></a></div></section>
<section class="journal"><div class="section-title"><div><p class="kicker">THE BLOG</p><h2>Stories from<br><em>the islands.</em></h2></div><a class="under" href="{{ route('blog.index') }}">VIEW ALL POSTS →</a></div><div class="posts">@foreach($posts as $post) @php($postImage=str_starts_with($post->featured_image ?? '','http')?$post->featured_image:asset('storage/'.$post->featured_image))<article><a href="{{ route('blog.show',$post) }}"><img src="{{ $postImage }}" alt=""><p class="kicker">{{ strtoupper($post->category) }}</p><h3>{{ $post->title }}</h3><p>{{ $post->excerpt }}</p><span>READ POST →</span></a></article>@endforeach</div></section>
<section class="enquiry"><div><p class="kicker">PERSONAL TRAVEL PLANNING</p><h2>Tell us what you<br><em>have in mind.</em></h2><p>Share a few details and our team will help shape the right Maldives journey for you.</p></div><form method="post" action="{{ route('inquiries.store') }}">@csrf @if(session('success'))<p class="success">{{ session('success') }}</p>@endif<div class="form-grid"><label>Your name<input name="name" required value="{{ old('name') }}"></label><label>WhatsApp number<input name="phone" required value="{{ old('phone') }}"></label><label>Travel type<select name="travel_type"><option value="resort">Resort</option><option value="guesthouse">Guesthouse</option><option value="liveaboard">Liveaboard</option></select></label><label>Preferred date<input type="date" name="travel_date"></label><label>Travellers<input type="number" name="travellers" min="1" value="2"></label><label>Approximate budget<input name="budget" placeholder="e.g. USD 3,000"></label><label class="wide">Anything else?<textarea name="message" rows="4" placeholder="Tell us about your ideal trip"></textarea></label></div><button>REQUEST A TRIP PLAN →</button></form></section>
<section class="closing"><p class="kicker pale">YOUR JOURNEY BEGINS HERE</p><h2>Let’s create something<br><em>unforgettable.</em></h2><a href="{{ $wa }}" target="_blank">START PLANNING ON WHATSAPP <span>↗</span></a></section>
@include('partials.site-footer')<a class="mobile-cta" href="{{ $wa }}" target="_blank">PLAN ON WHATSAPP <span>↗</span></a>
</main>@endsection
