<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\AccommodationController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InquiryController;
use App\Http\Controllers\LiveaboardController;
use App\Http\Controllers\OperationsDocumentDownloadController;
use App\Http\Controllers\OperationsImportTemplateController;
use App\Http\Controllers\QuotationPrintController;
use App\Http\Controllers\RequestQuoteController;
use App\Http\Controllers\RobotsController;
use App\Http\Controllers\SeoRedirectFallbackController;
use App\Http\Controllers\SitemapController;
use Illuminate\Support\Facades\Route;

Route::get('/robots.txt', RobotsController::class)->name('seo.robots');
Route::get('/sitemap.xml', SitemapController::class)->name('seo.sitemap');
Route::get('/', HomeController::class)->name('home');
Route::get('/about-us', AboutController::class)->name('about');
Route::get('/faq', FaqController::class)->name('faq');
Route::get('/liveaboards', LiveaboardController::class)->name('liveaboards.index');
Route::get('/liveaboards/{accommodation:slug}', [AccommodationController::class, 'liveaboardShow'])->name('liveaboards.show');
Route::get('/resorts', [AccommodationController::class, 'index'])->defaults('type', 'resort')->name('resorts.index');
Route::get('/resorts/{accommodation:slug}', [AccommodationController::class, 'resortShow'])->name('resorts.show');
Route::get('/guesthouses', [AccommodationController::class, 'index'])->defaults('type', 'guesthouse')->name('guesthouses.index');
Route::get('/guesthouses/{atoll:slug}', [AccommodationController::class, 'index'])->defaults('type', 'guesthouse')->name('guesthouses.atoll');
Route::get('/guesthouses/{atoll:slug}/{island:slug}', [AccommodationController::class, 'index'])->defaults('type', 'guesthouse')->name('guesthouses.island');
Route::get('/guesthouses/{atoll:slug}/{island:slug}/{accommodation:slug}', [AccommodationController::class, 'guesthouseShow'])->name('guesthouses.show');
Route::redirect('/guest-houses', '/guesthouses', 301);
Route::get('/city-hotels', [AccommodationController::class, 'index'])->defaults('type', 'city_hotel')->name('cityhotels.index');
Route::get('/city-hotels/{accommodation:slug}', [AccommodationController::class, 'cityHotelShow'])->name('cityhotels.show');
Route::get('/packages', [AccommodationController::class, 'index'])->defaults('type', 'package')->name('packages.index');
Route::get('/packages/{category}/{accommodation:slug}', [AccommodationController::class, 'packageShow'])->name('packages.show');
Route::get('/travel-products', [AccommodationController::class, 'index'])->name('accommodations.index');
Route::get('/travel-products/{accommodation:slug}', [AccommodationController::class, 'legacyShow'])->name('accommodations.show');
Route::redirect('/stays', '/travel-products', 301);
Route::get('/stays/{accommodation:slug}', [AccommodationController::class, 'legacyShow']);
Route::redirect('/journal', '/blog', 301);
Route::redirect('/journal/{post}', '/blog/{post}', 301);
Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('/blog/{post}', [BlogController::class, 'show'])->name('blog.show');
Route::get('/request-quote', RequestQuoteController::class)->name('request-quote');
Route::post('/inquiries', [InquiryController::class, 'store'])->middleware('throttle:5,1')->name('inquiries.store');
Route::get('/admin/operations/documents/{document}/download', OperationsDocumentDownloadController::class)->name('operations.documents.download');
Route::get('/admin/operations/import-templates/{type}', OperationsImportTemplateController::class)->name('operations.import-template');
Route::get('/admin/quotations/{quotation}/print', QuotationPrintController::class)->middleware('auth')->name('quotations.print');
Route::fallback(SeoRedirectFallbackController::class);
