<?php $__env->startSection('title','Micro Travel — Maldives, made personal'); ?>
<?php $__env->startSection('content'); ?>
<?php ($wa='https://wa.me/'.env('MICRO_TRAVEL_WHATSAPP','9609996210').'?text='.urlencode('Hello Micro Travel, I would like help planning a Maldives holiday.')); ?>
<main>
<?php echo $__env->make('partials.site-nav', ['whatsAppText' => 'Hello Micro Travel, I would like help planning a Maldives holiday.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="hero" style="background-image:url('<?php echo e($hero->hero_image_url); ?>')"><div class="shade"></div><div class="hero-copy"><p class="kicker pale"><?php echo e($hero->kicker); ?></p><h1><?php echo e($hero->heading_line_one); ?><br><?php echo e($hero->heading_line_two); ?> <em><?php echo e($hero->heading_emphasis); ?></em></h1><p><?php echo e($hero->description); ?></p></div>
<form class="finder" method="get" action="<?php echo e(route('accommodations.index')); ?>"><div class="tabs"><button type="button" class="active" data-tab="Resort">Resorts</button><button type="button" data-tab="Guesthouse">Guesthouses</button><button type="button" data-tab="Liveaboard">Liveaboards</button></div><input type="hidden" name="type" value="resort"><div class="fields"><label><small>WHERE</small><input name="atoll" placeholder="All atolls"></label><label><small>WHEN</small><input type="date" name="when"></label><label><small>TRAVELLERS</small><input type="number" name="travellers" value="2" min="1"></label><button>EXPLORE <span>→</span></button></div></form></section>
<section class="intro" id="about"><div><p class="kicker">MORE THAN A HOLIDAY</p><h2>The Maldives,<br><em>made personal.</em></h2></div><div><p>From your first question to your final seaplane, we make every detail feel effortless. Our Maldives-based team uses local knowledge to create a journey that feels entirely yours.</p><a class="under" href="<?php echo e($wa); ?>" target="_blank">TALK TO A LOCAL EXPERT <span>→</span></a></div></section>
<?php if (isset($component)) { $__componentOriginale96d91b2f25e6d8c6111f323b0bba4cf = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginale96d91b2f25e6d8c6111f323b0bba4cf = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.why-book-with-micro-travel','data' => []] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('why-book-with-micro-travel'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginale96d91b2f25e6d8c6111f323b0bba4cf)): ?>
<?php $attributes = $__attributesOriginale96d91b2f25e6d8c6111f323b0bba4cf; ?>
<?php unset($__attributesOriginale96d91b2f25e6d8c6111f323b0bba4cf); ?>
<?php endif; ?>
<?php if (isset($__componentOriginale96d91b2f25e6d8c6111f323b0bba4cf)): ?>
<?php $component = $__componentOriginale96d91b2f25e6d8c6111f323b0bba4cf; ?>
<?php unset($__componentOriginale96d91b2f25e6d8c6111f323b0bba4cf); ?>
<?php endif; ?>
<section class="stays" id="stays"><div class="section-title"><div><p class="kicker">STAY YOUR WAY</p><h2>Places worth<br><em>travelling for.</em></h2></div><p>Resorts, guesthouses, and liveaboards selected for their character, care, and sense of place.</p></div><div class="cards">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $featuredStays; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $stay): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php ($image=str_starts_with($stay->cover_image,'http')?$stay->cover_image:asset('storage/'.$stay->cover_image)); ?>
<article><a href="<?php echo e(route('accommodations.show',$stay)); ?>"><div class="photo"><img src="<?php echo e($image); ?>" alt="<?php echo e($stay->name); ?>"><small><?php echo e(str_pad($loop->iteration,2,'0',STR_PAD_LEFT)); ?></small></div><div class="meta"><span><?php echo e(strtoupper($stay->type->label())); ?></span><span><?php echo e($stay->island); ?></span></div><h3><?php echo e($stay->name); ?></h3><div class="foot"><span><?php echo e($stay->tagline); ?></span><b>FROM <?php echo e($stay->currency); ?> <?php echo e(number_format($stay->price_from)); ?></b></div></a></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> <p>Add featured accommodation from the admin panel.</p> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div><a class="outline" href="<?php echo e(route('accommodations.index')); ?>">EXPLORE ALL STAYS <span>→</span></a></section>
<section class="experience" id="experiences"><div class="exp-image"><span>▶</span></div><div class="exp-copy"><p class="kicker pale">BEYOND THE BLUE</p><h2>Come for the islands.<br><em>Remember the feeling.</em></h2><p>Drift with manta rays. Share breakfast on an empty sandbank. Learn the rhythm of island life from the people who call it home.</p><a class="under" href="<?php echo e($wa); ?>" target="_blank">DISCOVER EXPERIENCES <span>→</span></a></div></section>
<section class="journal"><div class="section-title"><div><p class="kicker">THE BLOG</p><h2>Stories from<br><em>the islands.</em></h2></div><a class="under" href="<?php echo e(route('blog.index')); ?>">VIEW ALL POSTS →</a></div><div class="posts"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $posts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $post): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php ($postImage=str_starts_with($post->featured_image ?? '','http')?$post->featured_image:asset('storage/'.$post->featured_image)); ?><article><a href="<?php echo e(route('blog.show',$post)); ?>"><img src="<?php echo e($postImage); ?>" alt=""><p class="kicker"><?php echo e(strtoupper($post->category)); ?></p><h3><?php echo e($post->title); ?></h3><p><?php echo e($post->excerpt); ?></p><span>READ POST →</span></a></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
<section class="enquiry"><div><p class="kicker">PERSONAL TRAVEL PLANNING</p><h2>Tell us what you<br><em>have in mind.</em></h2><p>Share a few details and our team will help shape the right Maldives journey for you.</p></div><form method="post" action="<?php echo e(route('inquiries.store')); ?>"><?php echo csrf_field(); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><p class="success"><?php echo e(session('success')); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><div class="form-grid"><label>Your name<input name="name" required value="<?php echo e(old('name')); ?>"></label><label>WhatsApp number<input name="phone" required value="<?php echo e(old('phone')); ?>"></label><label>Travel type<select name="travel_type"><option value="resort">Resort</option><option value="guesthouse">Guesthouse</option><option value="liveaboard">Liveaboard</option></select></label><label>Preferred date<input type="date" name="travel_date"></label><label>Travellers<input type="number" name="travellers" min="1" value="2"></label><label>Approximate budget<input name="budget" placeholder="e.g. USD 3,000"></label><label class="wide">Anything else?<textarea name="message" rows="4" placeholder="Tell us about your ideal trip"></textarea></label></div><button>REQUEST A TRIP PLAN →</button></form></section>
<section class="closing"><p class="kicker pale">YOUR JOURNEY BEGINS HERE</p><h2>Let’s create something<br><em>unforgettable.</em></h2><a href="<?php echo e($wa); ?>" target="_blank">START PLANNING ON WHATSAPP <span>↗</span></a></section>
<?php echo $__env->make('partials.site-footer', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><a class="mobile-cta" href="<?php echo e($wa); ?>" target="_blank">PLAN ON WHATSAPP <span>↗</span></a>
</main><?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/munad/Documents/Micro Travel/Micro-Travel-Laravel/resources/views/home.blade.php ENDPATH**/ ?>